import { Capacitor } from "@capacitor/core";
import { useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import { canExportReport, buildReportFilename } from "../data/reportExport";
import { collectPatientQuestions } from "../auditAdvocacyUtils";
import { hasActionablePlan } from "../actionPlanUtils";
import {
  downloadReportPdf,
  loadReportPdfBlobUrl,
  openNativePdfViewer,
  revokeReportPdfBlobUrl,
  shareReportPdf,
} from "../services/reportPdf";
import ReportPdfViewer from "./ReportPdfViewer";
import ActionConsentModal from "./ActionConsentModal";
import {
  hasActionConsent,
  setActionConsentAccepted,
} from "../services/localActionConsentStore";
import { POSSIBLE_ISSUE_NOTICE } from "../data/hedgingCopy";

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function printQuestionsOnly(report) {
  const questions = collectPatientQuestions(report);
  if (!questions.length) {
    return { ok: false, message: "No questions are available to print yet." };
  }

  const diagnosis =
    report?.diagnosis ||
    report?.prescription?.diagnosis ||
    report?.treatment_audit_flags?.matched_stg_conditions?.[0] ||
    "";
  const patientName = report?.patient?.name || "";
  const hospital = report?.hospital?.name_from_bill || "";
  const html = `<!DOCTYPE html>
<html><head><title>Questions for hospital</title>
<meta charset="utf-8" />
<style>
  body { font-family: Arial, sans-serif; padding: 24px; color: #1a1a1a; }
  h1 { font-size: 20px; }
  ol { line-height: 1.6; }
  .meta { margin-bottom: 16px; font-size: 14px; }
  .footer { margin-top: 24px; font-size: 12px; color: #555; }
</style></head><body>
<h1>Questions to ask the hospital</h1>
<div class="meta">
  ${patientName ? `<p><strong>Patient:</strong> ${escapeHtml(patientName)}</p>` : ""}
  ${hospital ? `<p><strong>Hospital:</strong> ${escapeHtml(hospital)}</p>` : ""}
  ${diagnosis ? `<p><strong>Diagnosis:</strong> ${escapeHtml(diagnosis)}</p>` : ""}
</div>
<ol>
  ${questions.map((q) => `<li>${escapeHtml(q.question)}</li>`).join("")}
</ol>
<p class="footer">Generated by Swaasth. ${escapeHtml(POSSIBLE_ISSUE_NOTICE)} These are clarification questions, not medical or legal findings.</p>
</body></html>`;

  const iframe = document.createElement("iframe");
  iframe.setAttribute("aria-hidden", "true");
  iframe.style.position = "fixed";
  iframe.style.width = "0";
  iframe.style.height = "0";
  iframe.style.border = "0";
  iframe.style.opacity = "0";
  iframe.style.pointerEvents = "none";
  document.body.appendChild(iframe);

  const frameWindow = iframe.contentWindow;
  const frameDoc = iframe.contentDocument || frameWindow?.document;
  if (!frameDoc || !frameWindow) {
    iframe.remove();
    return { ok: false, message: "Could not open the print preview." };
  }

  frameDoc.open();
  frameDoc.write(html);
  frameDoc.close();
  frameWindow.focus();
  frameWindow.print();

  window.setTimeout(() => {
    iframe.remove();
  }, 1000);

  return { ok: true };
}

function actionErrorMessage(error, fallback) {
  if (error?.message) {
    return error.message;
  }
  return fallback;
}

export default function ReportActions({ report, className = "report-actions" }) {
  const navigate = useNavigate();
  const [pdfMessage, setPdfMessage] = useState("");
  const [pdfMessageTone, setPdfMessageTone] = useState("error");
  const [busy, setBusy] = useState("");
  const [viewer, setViewer] = useState(null);
  const [showActionConsent, setShowActionConsent] = useState(false);
  const [exportOptions, setExportOptions] = useState({
    include_stg_excerpts: true,
    include_legal_pathways: true,
  });
  const pdfCacheRef = useRef({ blob: null, blobUrl: "", filename: "", title: "", optionsKey: "" });

  useEffect(() => {
    return () => {
      revokeReportPdfBlobUrl(pdfCacheRef.current.blobUrl);
      pdfCacheRef.current = { blob: null, blobUrl: "", filename: "", title: "" };
    };
  }, [report]);

  if (!canExportReport(report)) {
    return null;
  }

  const filename = buildReportFilename(report);
  const hasQuestions = collectPatientQuestions(report).length > 0;
  const hasActionPlan = hasActionablePlan(report);

  const navigateToAction = () => {
    const savedId =
      report?.id || report?.firestoreId || report?.localId || null;
    const path = savedId ? `/action/${savedId}` : "/action";
    navigate(path, { state: { report } });
  };

  const handleTakeAction = () => {
    if (hasActionConsent()) {
      navigateToAction();
      return;
    }
    setShowActionConsent(true);
  };

  const handleActionConsentAccept = () => {
    setActionConsentAccepted();
    setShowActionConsent(false);
    navigateToAction();
  };

  const handleActionConsentDecline = () => {
    setShowActionConsent(false);
  };

  const exportOptionsKey = JSON.stringify(exportOptions);

  const ensurePdf = async () => {
    if (pdfCacheRef.current.blob && pdfCacheRef.current.optionsKey === exportOptionsKey) {
      return pdfCacheRef.current;
    }
    revokeReportPdfBlobUrl(pdfCacheRef.current.blobUrl);
    const loaded = await loadReportPdfBlobUrl(report, exportOptions);
    pdfCacheRef.current = { ...loaded, optionsKey: exportOptionsKey };
    return loaded;
  };

  const closeViewer = () => {
    setViewer(null);
  };

  const showMessage = (message, tone = "error") => {
    setPdfMessage(message);
    setPdfMessageTone(tone);
  };

  const handleView = async () => {
    setBusy("view");
    showMessage("");
    try {
      const loaded = await ensurePdf();
      if (Capacitor.isNativePlatform()) {
        const outcome = await openNativePdfViewer(
          loaded.blob,
          loaded.filename,
          loaded.title
        );
        if (outcome.cancelled) {
          return;
        }
        setViewer({
          blobUrl: loaded.blobUrl,
          title: loaded.title,
          nativeFallback: true,
        });
        showMessage(
          outcome.opened
            ? "PDF opened in your viewer. Use Download or Share below if needed."
            : "Use Download or Share below to open the report.",
          "info"
        );
        return;
      }
      setViewer({
        blobUrl: loaded.blobUrl,
        title: loaded.title,
      });
    } catch (error) {
      showMessage(
        actionErrorMessage(
          error,
          "Could not open the report. Check your connection and try again."
        )
      );
    } finally {
      setBusy("");
    }
  };

  const handleDownload = async () => {
    setBusy("download");
    showMessage("");
    try {
      const loaded = await ensurePdf();
      const outcome = await downloadReportPdf(report, filename, loaded.blob);
      if (outcome.method === "download" && outcome.path) {
        showMessage(`Report saved to ${outcome.path}.`, "info");
      }
    } catch (error) {
      showMessage(
        actionErrorMessage(
          error,
          "Could not download the report. Check your connection and try again."
        )
      );
    } finally {
      setBusy("");
    }
  };

  const handleShare = async () => {
    setBusy("share");
    showMessage("");
    try {
      const loaded = await ensurePdf();
      const outcome = await shareReportPdf(report, loaded.blob);
      if (outcome.cancelled) {
        return;
      }
      if (!outcome.shared) {
        setViewer({
          blobUrl: loaded.blobUrl,
          title: loaded.title,
          nativeFallback: Capacitor.isNativePlatform(),
        });
        showMessage(
          outcome.needsPreview
            ? "Opened the report preview — use Download or Share there."
            : "Sharing isn't supported here — opened the report viewer instead.",
          "info"
        );
      } else if (outcome.method === "text") {
        showMessage("Shared report title. Use Download to save the PDF file.", "info");
      }
    } catch (error) {
      showMessage(
        actionErrorMessage(error, "Could not share the report.")
      );
    } finally {
      setBusy("");
    }
  };

  const handlePrintQuestions = () => {
    setBusy("questions");
    showMessage("");
    try {
      const outcome = printQuestionsOnly(report);
      if (!outcome.ok) {
        showMessage(outcome.message);
      }
    } finally {
      setBusy("");
    }
  };

  return (
    <>
      {pdfMessage && (
        <p
          className={
            pdfMessageTone === "info"
              ? "auth-info report-actions-message"
              : "error-text report-actions-message"
          }
        >
          {pdfMessage}
        </p>
      )}
      <div className="report-export-options">
        <p className="report-export-options-label">PDF export includes:</p>
        <label className="report-export-option">
          <input
            type="checkbox"
            checked={exportOptions.include_stg_excerpts}
            onChange={(event) => {
              setExportOptions((prev) => ({
                ...prev,
                include_stg_excerpts: event.target.checked,
              }));
              pdfCacheRef.current = { blob: null, blobUrl: "", filename: "", title: "", optionsKey: "" };
            }}
          />
          Full STG guideline paragraphs
        </label>
        <label className="report-export-option">
          <input
            type="checkbox"
            checked={exportOptions.include_legal_pathways}
            onChange={(event) => {
              setExportOptions((prev) => ({
                ...prev,
                include_legal_pathways: event.target.checked,
              }));
              pdfCacheRef.current = { blob: null, blobUrl: "", filename: "", title: "", optionsKey: "" };
            }}
          />
          Educational legal pathway notes
        </label>
      </div>
      <div className={className}>
        {hasActionPlan && (
          <button
            type="button"
            className="analyze-btn report-take-action-btn"
            onClick={handleTakeAction}
            disabled={Boolean(busy)}
          >
            Take action / Dispute
          </button>
        )}
        {hasQuestions && (
          <button
            type="button"
            className="bill-editor-secondary"
            onClick={handlePrintQuestions}
            disabled={Boolean(busy)}
          >
            {busy === "questions" ? "Preparing…" : "Print questions for billing"}
          </button>
        )}
        <button
          type="button"
          className="bill-editor-secondary"
          onClick={handleView}
          disabled={Boolean(busy)}
        >
          {busy === "view" ? "Opening…" : "View Full Report"}
        </button>
        <button
          type="button"
          className="bill-editor-secondary"
          onClick={handleDownload}
          disabled={Boolean(busy)}
        >
          {busy === "download" ? "Preparing…" : "Download Report"}
        </button>
        <button
          type="button"
          className="analyze-btn report-share-btn"
          onClick={handleShare}
          disabled={Boolean(busy)}
        >
          {busy === "share" ? "Sharing…" : "Share Report"}
        </button>
      </div>

      {viewer && (
        <ReportPdfViewer
          blobUrl={viewer.blobUrl}
          title={viewer.title}
          onClose={closeViewer}
          onDownload={handleDownload}
          onShare={handleShare}
          busyAction={busy}
          nativeFallback={Boolean(viewer.nativeFallback)}
        />
      )}

      {showActionConsent && (
        <ActionConsentModal
          onAccept={handleActionConsentAccept}
          onDecline={handleActionConsentDecline}
        />
      )}
    </>
  );
}
