import { useState } from "react";
import { canExportReport, buildReportFilename } from "../data/schemes";
import { collectPatientQuestions } from "../auditAdvocacyUtils";
import {
  downloadReportPdf,
  openReportPdf,
  shareReportPdf,
} from "../services/reportPdf";

function printQuestionsOnly(report) {
  const questions = collectPatientQuestions(report);
  const diagnosis =
    report?.diagnosis ||
    report?.prescription?.diagnosis ||
    report?.treatment_audit_flags?.matched_stg_conditions?.[0] ||
    "";
  const patientName = report?.patient?.name || "";
  const hospital = report?.hospital?.name_from_bill || "";
  const html = `
    <html><head><title>Questions for hospital</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 24px; color: #1a1a1a; }
      h1 { font-size: 20px; }
      ol { line-height: 1.6; }
      .meta { margin-bottom: 16px; font-size: 14px; }
      .footer { margin-top: 24px; font-size: 12px; color: #555; }
    </style></head><body>
    <h1>Questions to ask the hospital</h1>
    <div class="meta">
      ${patientName ? `<p><strong>Patient:</strong> ${patientName}</p>` : ""}
      ${hospital ? `<p><strong>Hospital:</strong> ${hospital}</p>` : ""}
      ${diagnosis ? `<p><strong>Diagnosis:</strong> ${diagnosis}</p>` : ""}
    </div>
    <ol>
      ${questions.map((q) => `<li>${q.question}</li>`).join("")}
    </ol>
    <p class="footer">Generated by Swaasth. These are clarification questions, not medical or legal findings.</p>
    </body></html>`;
  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) {
    return false;
  }
  win.document.write(html);
  win.document.close();
  win.focus();
  win.print();
  return true;
}

export default function ReportActions({ report, className = "report-actions" }) {
  const [pdfMessage, setPdfMessage] = useState("");
  const [busy, setBusy] = useState("");

  if (!canExportReport(report)) {
    return null;
  }

  const filename = buildReportFilename(report);
  const hasQuestions = collectPatientQuestions(report).length > 0;

  const handleView = async () => {
    setBusy("view");
    setPdfMessage("");
    try {
      await openReportPdf(report);
    } catch {
      setPdfMessage("Could not open the report. Check your connection and try again.");
    } finally {
      setBusy("");
    }
  };

  const handleDownload = async () => {
    setBusy("download");
    setPdfMessage("");
    try {
      await downloadReportPdf(report, filename);
    } catch {
      setPdfMessage("Could not download the report. Check your connection and try again.");
    } finally {
      setBusy("");
    }
  };

  const handleShare = async () => {
    setBusy("share");
    setPdfMessage("");
    try {
      const shared = await shareReportPdf(report);
      if (!shared) {
        setPdfMessage("Sharing isn't supported here — opened the report instead.");
      }
    } catch {
      setPdfMessage("Could not share the report.");
    } finally {
      setBusy("");
    }
  };

  const handlePrintQuestions = () => {
    setBusy("questions");
    setPdfMessage("");
    try {
      const ok = printQuestionsOnly(report);
      if (!ok) {
        setPdfMessage("Could not open print view. Allow pop-ups and try again.");
      }
    } finally {
      setBusy("");
    }
  };

  return (
    <>
      <div className={className}>
        {hasQuestions && (
          <button
            type="button"
            className="bill-editor-secondary"
            onClick={handlePrintQuestions}
            disabled={busy === "questions"}
          >
            {busy === "questions" ? "Preparing…" : "Print questions for billing"}
          </button>
        )}
        <button
          type="button"
          className="bill-editor-secondary"
          onClick={handleView}
          disabled={busy === "view"}
        >
          {busy === "view" ? "Opening…" : "View Full Report"}
        </button>
        <button
          type="button"
          className="bill-editor-secondary"
          onClick={handleDownload}
          disabled={busy === "download"}
        >
          {busy === "download" ? "Preparing…" : "Download Report"}
        </button>
        <button
          type="button"
          className="analyze-btn report-share-btn"
          onClick={handleShare}
          disabled={busy === "share"}
        >
          {busy === "share" ? "Sharing…" : "Share Report"}
        </button>
      </div>
      {pdfMessage && <p className="auth-info">{pdfMessage}</p>}
    </>
  );
}
