import { useState } from "react";
import { canExportReport, buildReportFilename } from "../data/schemes";
import { collectPatientQuestions } from "../auditAdvocacyUtils";
import {
  downloadReportPdf,
  openReportPdf,
  shareReportPdf,
} from "../services/reportPdf";

function escapeHtml(value) {
  return String(value ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function printQuestionsOnly(report) {
  const questions = collectPatientQuestions(report);
  if (!questions.length) {
    return { ok: false, message: "No questions are available to print yet." };
  }

  const diagnosis =
    report?.diagnosis ||
    report?.prescription?.diagnosis ||
    report?.treatment_audit_flags?.matched_stg_conditions?.[0] ||
    "";
  const patientName = report?.patient?.name || "";
  const hospital = report?.hospital?.name_from_bill || "";
  const html = `<!DOCTYPE html>
<html><head><title>Questions for hospital</title>
<meta charset="utf-8" />
<style>
  body { font-family: Arial, sans-serif; padding: 24px; color: #1a1a1a; }
  h1 { font-size: 20px; }
  ol { line-height: 1.6; }
  .meta { margin-bottom: 16px; font-size: 14px; }
  .footer { margin-top: 24px; font-size: 12px; color: #555; }
</style></head><body>
<h1>Questions to ask the hospital</h1>
<div class="meta">
  ${patientName ? `<p><strong>Patient:</strong> ${escapeHtml(patientName)}</p>` : ""}
  ${hospital ? `<p><strong>Hospital:</strong> ${escapeHtml(hospital)}</p>` : ""}
  ${diagnosis ? `<p><strong>Diagnosis:</strong> ${escapeHtml(diagnosis)}</p>` : ""}
</div>
<ol>
  ${questions.map((q) => `<li>${escapeHtml(q.question)}</li>`).join("")}
</ol>
<p class="footer">Generated by Swaasth. These are clarification questions, not medical or legal findings.</p>
</body></html>`;

  const preview = window.open("about:blank", "_blank", "noopener,noreferrer");
  if (!preview) {
    return {
      ok: false,
      message: "Pop-up blocked. Allow pop-ups for this site and try again.",
    };
  }
  preview.document.open();
  preview.document.write(html);
  preview.document.close();
  preview.focus();
  preview.print();
  return { ok: true };
}

function actionErrorMessage(error, fallback) {
  if (error?.message) {
    return error.message;
  }
  return fallback;
}

export default function ReportActions({ report, className = "report-actions" }) {
  const [pdfMessage, setPdfMessage] = useState("");
  const [busy, setBusy] = useState("");

  if (!canExportReport(report)) {
    return null;
  }

  const filename = buildReportFilename(report);
  const hasQuestions = collectPatientQuestions(report).length > 0;

  const handleView = async () => {
    setBusy("view");
    setPdfMessage("");
    try {
      await openReportPdf(report);
    } catch (error) {
      setPdfMessage(
        actionErrorMessage(
          error,
          "Could not open the report. Check your connection and try again."
        )
      );
    } finally {
      setBusy("");
    }
  };

  const handleDownload = async () => {
    setBusy("download");
    setPdfMessage("");
    try {
      await downloadReportPdf(report, filename);
    } catch (error) {
      setPdfMessage(
        actionErrorMessage(
          error,
          "Could not download the report. Check your connection and try again."
        )
      );
    } finally {
      setBusy("");
    }
  };

  const handleShare = async () => {
    setBusy("share");
    setPdfMessage("");
    try {
      const shared = await shareReportPdf(report);
      if (!shared) {
        setPdfMessage("Sharing isn't supported here — opened the report in a new tab instead.");
      }
    } catch (error) {
      setPdfMessage(
        actionErrorMessage(error, "Could not share the report.")
      );
    } finally {
      setBusy("");
    }
  };

  const handlePrintQuestions = () => {
    setBusy("questions");
    setPdfMessage("");
    try {
      const outcome = printQuestionsOnly(report);
      if (!outcome.ok) {
        setPdfMessage(outcome.message);
      }
    } finally {
      setBusy("");
    }
  };

  return (
    <>
      {pdfMessage && <p className="error-text report-actions-message">{pdfMessage}</p>}
      <div className={className}>
        {hasQuestions && (
          <button
            type="button"
            className="bill-editor-secondary"
            onClick={handlePrintQuestions}
            disabled={Boolean(busy)}
          >
            {busy === "questions" ? "Preparing…" : "Print questions for billing"}
          </button>
        )}
        <button
          type="button"
          className="bill-editor-secondary"
          onClick={handleView}
          disabled={Boolean(busy)}
        >
          {busy === "view" ? "Opening…" : "View Full Report"}
        </button>
        <button
          type="button"
          className="bill-editor-secondary"
          onClick={handleDownload}
          disabled={Boolean(busy)}
        >
          {busy === "download" ? "Preparing…" : "Download Report"}
        </button>
        <button
          type="button"
          className="analyze-btn report-share-btn"
          onClick={handleShare}
          disabled={Boolean(busy)}
        >
          {busy === "share" ? "Sharing…" : "Share Report"}
        </button>
      </div>
    </>
  );
}
