import { collectPatientQuestions } from "../auditAdvocacyUtils";
import { flagDisplayLabel } from "../auditAdvocacyUtils";
import { POSSIBLE_ISSUE_NOTICE } from "../data/hedgingCopy";
import {
  buildFlagKey,
  collectAllFlags,
  normalizeClinicianAnnotations,
} from "./reportAnnotations";
import { resolveReportMeta } from "../data/reportExport";
import { confirmPhiExport } from "./confirmPhiExport";

function formatFlagSection(report, annotations) {
  const flags = collectAllFlags(report);
  if (!flags.length) {
    return "";
  }

  const normalized = normalizeClinicianAnnotations(annotations);
  const lines = ["Findings to discuss:"];

  flags.forEach((flag, index) => {
    const label = flag.display_label || flagDisplayLabel(flag.type);
    const title = flag.item ? `${label} — ${flag.item}` : label;
    lines.push("");
    lines.push(`${index + 1}. ${title}`);
    if (flag.reason) {
      lines.push(`   Reason: ${flag.reason}`);
    }
    if (flag.recommendation) {
      lines.push(`   Question: ${flag.recommendation}`);
    }
    const note = normalized.flag_notes[buildFlagKey(flag, index)]?.text;
    if (note) {
      lines.push(`   Patient note: ${note}`);
    }
  });

  return lines.join("\n");
}

export function buildClinicianShareText(report, annotations = null) {
  const meta = resolveReportMeta(report);
  const patientName = report?.patient?.name || "Patient";
  const diagnosis =
    report?.diagnosis ||
    report?.prescription?.diagnosis ||
    report?.treatment_audit_flags?.matched_stg_conditions?.[0] ||
    "";
  const hospital =
    report?.hospital?.name_from_bill ||
    report?.hospital_profile?.name ||
    "";
  const normalized = normalizeClinicianAnnotations(
    annotations || report?.clinician_annotations
  );
  const questions = collectPatientQuestions(report);

  const lines = [
    "Swaasth — summary for clinician review",
    "",
    `Report: ${meta.reportTitle}`,
    `Patient: ${patientName}`,
  ];

  if (hospital) {
    lines.push(`Hospital: ${hospital}`);
  }
  if (diagnosis) {
    lines.push(`Diagnosis under review: ${diagnosis}`);
  }

  const symptoms = report?.clinical_context?.symptoms || [];
  if (symptoms.length) {
    lines.push(
      `Symptoms: ${symptoms.map((item) => item.name).filter(Boolean).join(", ")}`
    );
  }

  const testResults = report?.clinical_context?.test_results || [];
  if (testResults.length) {
    lines.push("Test results:");
    for (const result of testResults) {
      const parts = [
        result.test_name,
        result.value,
        result.unit,
        result.result,
        result.reference_range ? `(ref ${result.reference_range})` : "",
      ].filter(Boolean);
      lines.push(`- ${parts.join(" ")}`);
    }
  }

  if (normalized.general_note) {
    lines.push("");
    lines.push("Patient / caregiver note:");
    lines.push(normalized.general_note);
  }

  const flagSection = formatFlagSection(report, normalized);
  if (flagSection) {
    lines.push("");
    lines.push(flagSection);
  }

  if (questions.length) {
    lines.push("");
    lines.push("Suggested questions:");
    questions.forEach((entry, index) => {
      lines.push(`${index + 1}. ${entry.question}`);
    });
  }

  lines.push("");
  lines.push(
    `${POSSIBLE_ISSUE_NOTICE} This summary was generated by Swaasth to support clarification and shared decision-making. It is not a medical diagnosis or legal finding.`
  );

  return lines.join("\n");
}

export async function shareClinicianSummary(report, annotations = null) {
  if (
    !confirmPhiExport(
      "This will share medical information outside the app (share sheet or clipboard). Continue?"
    )
  ) {
    return { shared: false, cancelled: true };
  }

  const text = buildClinicianShareText(report, annotations);
  const title = `Swaasth summary — ${report?.patient?.name || "patient"}`;

  if (typeof navigator !== "undefined" && navigator.share) {
    try {
      await navigator.share({ title, text });
      return { shared: true, method: "native" };
    } catch (error) {
      if (error?.name === "AbortError") {
        return { shared: false, cancelled: true };
      }
    }
  }

  if (typeof navigator !== "undefined" && navigator.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return { shared: true, method: "clipboard" };
  }

  return { shared: false, text };
}
